apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: work-app-hpa
  namespace: lab3
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: work-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: work_active_requests_hpa
      target:
        type: AverageValue
        averageValue: "50" 
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0 
      policies:
      - type: Pods
        value: 4 
        periodSeconds: 10