apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: work-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: work.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: work-app
            port:
              number: 80